### ISSUE TITLE
Peer-To-Peer Code Review

### ISSUE THREAD

**Issue by Kgomotso196** [ticoniq/Leaderboard#3]
Hello @ticoniq , I'm impressed on the implementation of your project. However, there's a little issue you might want to consider working on.
https://github.com/ticoniq/Leaderboard/blob/cc4741bc2f5d1fc9bb474394f59b6030f6b74b43/src/index.js#L86
Kindly, utilize descriptive variable names;  `ul` is not descriptive enough to tell what it does.

**Comment by Paulinelali** [comment]
That was great @ticoniq great coding😎

**Comment by ticoniq** [comment]
Thanks for the feedback
